######################################################################
# Automatically generated by qmake (3.0) Sat Oct 24 20:32:16 2015
######################################################################

TEMPLATE = app
TARGET = qyomi
INCLUDEPATH += .

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

# Input
HEADERS += dicttool.h furiganabox.h globs.h mainwindow.h mecabtool.h
SOURCES += dicttool.cpp furiganabox.cpp main.cpp mainwindow.cpp mecabtool.cpp

LIBS += -lmecab
